### PR TITLE
Fix issues when a `config.rb` file is present somewhere in the directories

### PR DESCRIPTION
**Pull request by sztupy**
In this case the `config.yml` or `config.json` files might not get parsed, resulting in missing configuration values, and/or errors

### CODE REVIEW

**Comment by sztupy** [comment]
It seems it also fixes the issue with the `config.yml` file not being picked up in the default generated blog (where there is a `config.ru` file in the root)

**Comment by indolent-gnathostome** [comment]
Much appreciated, @sztupy; especially the new test.  It looks like changes to `lib/ruhoh/config.rb` in this commit are relevant to #257, #256, #254, and #251.

**Comment by sztupy** [comment]
Ah, found a bug with loading the config files from the subdirectories. Fixed and added tests for it

**Comment by plusjade** [comment]
@sztupy much appreciated! Sorry I haven't been around lately and it has taken me a while to merge this in.

**Pull request merged**
