### PR TITLE
Added RSS Support

### PR DESCRIPTION
**Pull request by davejlong**
When the `compile` command is run rss.xml will be generated in the compile directory.

### CODE REVIEW

**Comment by davejlong** [comment]
Closes Issue #14

**Comment by plusjade** [comment]
@davejlong sorry for the late response. This looks well done and will definitely be added to 0.2.0. I may have to do this manually though since this pull is based of the master.  I'm super hesitant to require gem dependencies unless absolutely necessary. I see nokogiri is required for this to work, but a robust rss feed is _probably_ a very necessary feature for a blog. Also nokogiri is a very useful gems which most rubyists already use. 

Thank you for your time and work on this Dave. Look for 0.2.0 in the next week.

**Comment by plusjade** [comment]
@davejlong I provided your rss compiler task as an example for the new plugin system available in version 0.3.0. 

I'm going to close this ticket since it is no longer mergeable but we might add it to the man gem if enough people want automatic rss support, I just want require minimum dependencies for the time being.

Thank you for your work. I'll get an official plugins page up shortly to give you adequate credit. Any feedback on the plugin system?

Edit: For posterity, the RSS plugin can be found outlined here: http://ruhoh.com/usage/plugins/#toc_5

**Comment by orva** [comment]
> I'm thinking about adding this as a default task, but I'm hesitant to require the additional nokogiri dependency -- what do you think?

This was in plugin page mentioned at [5675040](https://github.com/ruhoh/ruhoh.rb/pull/18#issuecomment-5675040) so I thought to put my 2 cents here for public conversation:

I don't think that dependencies for Nokogiri (or any JSON) library can be though as "bad" thing when you are dealing with web related stuff. And if you truly think those are bad, they are necessarily evil that you just need to bear with. Also considering that there is most likely no one that would want to be without RSS/Atom feed, feed builder should be included into ruhoh.

**Comment by davejlong** [comment]
I agree, that the Nokogiri is useful for many things outside of just RSS, for example if someone wanted to build a page generator of their own as a plugin, or something like that. I understand what you mean @plusjade with regard to wanting to keep Ruhoh as lightweight as possible so that it is easier to implement into other languages, but I think that every programming language that I've used has an XML generation tool like Nokogiri.

That being said, generating the same RSS feed without Nokogiri shouldn't be too hard to do.

**Pull request closed without merging**
