### PR TITLE
Getting tests to pass

### LINKED ISSUE #19: Unable to run tests
Hi, I've forked the gem and tried to run the tests, but the output is this: http://pastebin.com/RTtDYuNm

### PR DESCRIPTION
**Pull request by ben-biddington**
Hi fellows,

I made some changes tests can run anywhere, and so they also pass on http://travis-ci.org/#!/ben-biddington/ruhoh.rb.
- Introduced local temporary directory as SampleSitePath with value <./__tmp>
- Fixed the layouts and page parser tests to create the files they expect
- Added travis config
- Enabled `bundle exec rake`

Also resolves https://github.com/ruhoh/ruhoh.rb/issues/19

<bb />

### CODE REVIEW

**Comment by plusjade** [comment]
@ben-biddington this is a really neat way to solve the problem of having files to test against. I've given this once over on my local machine and all looks good.

I will merge this request manually on my local machine and then commit the result when I finish the 0.2.0 branch. 0.2.0 provides a much more sane draft-publish workflow and a dashboard addition. I'll have to add documentation for all the changes though so please expect to see 0.2.0 in the next week or so.

Just to be clear I can't merge this directly into master because 0.2.0 is not finished yet. So this will be pending till 0.2.0 
Thank you for your time and work! 

Also can you tell me how I can update the readme to get the travis passing/failing notification on there?

**Comment by ben-biddington** [comment]
As above, @plusjade.

(Also, don't forget to edit `.travis.yml` to point to your fork.)

This's a cool gem, thanks ;-)

<bb />

**Comment by plusjade** [comment]
Thanks @ben-biddington, I've merged your updates into 0.2.0 which is now at HEAD. I haven't released the gem update yet though, still have documentation to write. 

I'm going to close this, but with an added todo to get the travis status setup for ruhoh master, as I haven't done that yet.

**Comment by Heliosmaster** [comment]
To get the status in the README, just follow as it is written here: http://about.travis-ci.org/docs/user/status-images/,

**Pull request closed without merging**
