### PR TITLE
Widgets Overhaul

### PR DESCRIPTION
**Pull request by caspervonb**
Was implementing a widget for prism.js and figured it would be a good fit to merge with prettify.

There is however one issue I'm not sure how to solve, so I'm submitting early for discussion.
CDN is configurable, but it is optional and prettify.js is bundled in the javascripts directory.
So when CDN is set prettify.js needs to be ignored but am unable to exclude it, thought that was what exclude was for but no success.

### CODE REVIEW

**Comment by plusjade** [comment]
To clarify, you want to be able to exclude files from the compiled output right?  Regarding exclusion rules, yes it should work but it might now work on a _per_widget_ basis. So the rules are probably not being applied in the right "scope" (the particular widget). Also since I removed all the tests I can't guarantee exclusion rules work reliably, but getting tests back in is certainly a priority on the list.

**Comment by caspervonb** [comment]
Yes want to exclude it from compilation
Could you outline an example that should work? tried a bunch of variations and can't seem to exclude anything from within a widget, stepping through the code at the moment trying to grok whats going on.

**Comment by caspervonb** [comment]
So it works on a widgets collection basis rather treating each widget as a seperate collection.

Works

``` yaml
widgets:
  exclude: '.*.js$'
```

Does not work

``` yaml
widgets:
  example:
    exclude: '.*.js$'
```

Consider it a bug? seems counter intuitive that the second example does not work.
At the very least the following seems inline with how ruhoh is structured.

``` yaml
widgets:
  example:
    javascripts:
      exclude: '.*.js$'
```

**Comment by plusjade** [comment]
Hmm, you do have a point. Currently widgets don't work the way you describe but if the point of widgets is customization, then your implementation makes more sense.

I'll consider this a bug.

**Comment by caspervonb** [comment]
Example use case for c9488a0f965f2b5d71575f479469857517f1bee5

### Structure

```
widgets/
  syntax/
    prism.html
    prettify.html
    javascripts/prism.js
    javascripts/prettify.js
...
```

### prism.html

``` html
---
# Exclude anything that is not related to prism.
exclude: '^((?!prism).)*$'
---
...
```

### prettify.html

``` html
---
# Exclude anything that is not related to prettify.
exclude: '^((?!prettify).)*$'
---
...
```

### Configuration

``` yaml
widgets: 
  syntax:
    use: prism
...
```

### Compilation output

```
Widgets: (copying valid files)
  > syntax/javascripts/prism.js
```

**Comment by plusjade** [comment]
:+1:

**Pull request merged**
