### PR TITLE
Allow post titles to have dates appended automatically

### PR DESCRIPTION
**Pull request by lynnfaraday**
Can use the {{DATE}} keyword in a new post:

```
ruhoh post "{{DATE}} New post"
```

### CODE REVIEW

**Comment by caspervonb** [comment]
In what way would this be useful?
You have the date in a separate field, which is set automatically.
You can use this however you see fit in the layout.

**Comment by lynnfaraday** [comment]
@caspervonb - I like to have my post files organized by date so I can find things easily.  I thought one of the other blog engines did the filenames like this automatically too, so perhaps I'm not the only one who likes it that way.

**Comment by caspervonb** [comment]
@lynnfaraday Well, i think it adds out of place bloat to the command.
There's no need for magic substitution inside of Ruhoh when you can just do shell substitution, say for example

``` bash
ruhoh post new `date +"%m-%d-%Y"`-foo
```

**Comment by caspervonb** [comment]
However, perhaps <resource> titleize should accept options to --prepend-date.

**Comment by lynnfaraday** [comment]
@caspervonb - Sure, no problem.  Feel free to close if you don't think it's useful.

**Comment by caspervonb** [comment]
Up to @plusjade, just giving my feedback for discussion.

**Comment by plusjade** [comment]
I didn't immediately get the use-case but now I understand that this changes the actual filepath rather then the in-file metadata. Dates in the filepath is a remnant of jekyll origins which was heavily deprecated (though pretty sure still works just not advertised) mainly to reduce complexity.

However to each his own, I think it's a cool trick. I won't add this in to the source only because the idea behind the abstracted client.rb classes is explicitly to provide custom implementations via plugins. Of course there is no documentation for it =/ but you can take a look at the [pages client](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/resources/pages/client.rb)

All public methods in this class are automatically available in the command line via the namespace. In this way you can add a ruby file to the plugin directory that looked something like this:

``` ruby
module Ruhoh::Resources::Pages
  class Client
    def new_with_date
      # @args <-- all command-line args are available in this hash
      # blah blah
    end
  end
end
```

Which can be called like:

```
$ ruhoh pages new_with_date blah blah
```

Alternatively you can re-implement the entire `#create` method instead of creating a new one.

In due time there will be better documentation and a cleaner api for all of this so ideally people can have full customization with their command-line experience.

**Comment by lynnfaraday** [comment]
@plusjade - Overriding the client works for me, thanks.   

FYI - The use case is that I have 6 years of blog posts in 1 directory, and without the dates in the filenames the lack of organization drives me batty.  I just thought I'd mention it in case it sparked any ideas.

**Comment by plusjade** [comment]
:+1:  I definitely get what you mean.  I imagine the inevitable truth regarding hundreds/thousands of posts will be "make a web-ui with search/browsr support by date, and then wth throw the data in a database so it's faster!  =P

I guess it would be much faster to do unix-level searching at that point though...who knows!

But point is definitely see the use-case, and will get the wheels turning regarding possible solutions.

**Pull request closed without merging**
